### ISSUE TITLE
[Bug] - Fix Camunda 7 Mapper 

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-connect#100]
**Describe the bug**
Miranum's Camunda 7 specific mapper does not recognise a String as primitive type and converts it to JSON. This leads to a SPIN deserialisation exception which is thrown in Camunda. 

**To Reproduce**
1. Create a method which returns an object which only contains a property of type String
2. Try to access the object via I/O mapping in the process 
4. See exception thrown / incident in Camunda

**Expected behavior**
A String is handled as a primitive type. 

```[tasklist]
### Tasks
- [x] add another or junction in the if statement which is responsible for identifying primitive types
- [x] fix simple-example project so it actually can work
- [x] fix documentation because variables in IO mappings get accessed by expressions (&{})
```

**Comment by Hafflgav** [comment]
FYI @rami-nk and @dominikhorn93
This is the reason why I ran into problems with my IO mappings yesterday. 
The example we have up in our docs as well as the example project need to be fixed as well. 

I pushed the fix to the branch: https://github.com/FlowSquad/miranum/tree/fix/Camunda7Mapper already. 
I would like to fix the simple example before merging it. I think I might be able to do so tomorrow.

**Comment by rami-nk** [comment]
> FYI @rami-nk and @dominikhorn93 This is the reason why I ran into problems with my IO mappings yesterday. The example we have up in our docs as well as the example project need to be fixed as well.
> 
> I pushed the fix to the branch: https://github.com/FlowSquad/miranum/tree/fix/Camunda7Mapper already. I would like to fix the simple example before merging it. I think I might be able to do so tomorrow.

Would be nice if you can link the pr's to the tasks on the board
