### ISSUE TITLE
[Fix] - Change annotation processing to not be iterative

### ISSUE THREAD

**Issue by rami-nk** [FlowSquad/miranum-connect#109]
- [x] Description created
- [ ] Reviewed by peer: @dominikhorn93 
- [x] Prioritised

# Issue
Currently we are using the ApplicationContextAware and an ApplicationReadyEvent to iterate get all beans in the current context and iterate over them to get the beans with worker or elementtemplate annotation to apply some action on those.

# Description
Instead of iterating over all beans you can hook into the spring bean lifecycle. The BeanPostProcessor interface provides functions that get called for every bean before and after initialization. Here you could check if a bean has a specific annotation and add it to a registry that gets gets queried and applies some function on the collected data.

## Sub-Tasks
 
- [ ] Change and evaluate for worker annotation processing
- [ ] Change for element template annotation processing
```[tasklist]
### Tasks
- [ ] <your-issue-here>
```
