### ISSUE TITLE
[Feature] - Create Element Template Generator for Camunda 8

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-connect#52]
- [x] Description created 
- [x] Reviewed by peer (24 hr window): <tag-person-here>
- [x] Prioritised

# Description 
As a developer I want to generate Element Templates from code to increase the reusability of the integrations I have written. This should be possible via a simple maven or gradle dependency. It saves me time not to create the JSON templates by myself and have them generated. 
This should apply for Camunda Platform 8. 

## Sub-Tasks 

```[tasklist]
### Tasks
- [ ]  Draft a prototype
- [ ]  Write test cases
- [ ]  Refactor
- [ ]  Create documentation
- [ ]  Release as maven or gradle dependency
```

**Comment by Hafflgav** [comment]
@peterhnm - looks about right! 👍

**Comment by peterhnm** [comment]
❓ @Hafflgav jsonschema2pojo does have problems generating pojos form this schema. @rami-nk descriped this in #51. Do I need to create the schema myself or am I using jsonschema2pojo incorrectly?

**Comment by Hafflgav** [comment]
> ❓ @Hafflgav jsonschema2pojo has problems generating pojos form this schema. @rami-nk descriped this in #51. Do I need to create the schema myself or am I using jsonschema2pojo incorrectly?

Puh, apparently I do not know this right away. Isn't this evident from the code @rami-nk  wrote for the C7 Element Template Generator?
